### ISSUE TITLE
Adding Support for Qt Quick Extras

### ISSUE THREAD

**Issue by hogandp** [JuliaGraphics/QML.jl#144]
I recently ran across QML.jl and love the blend of the Qt + Julia!

I would be interested in seeing the [Qt Quick Extras](https://doc.qt.io/qt-5/qtquick-extras-qmlmodule.html) package supported and would be willing to help get that going as I would like to use some of the UI controls in that package. 

If you have any notes or can point me in the correct direction I'd be willing to give it a go unless there is a technical / license issue.

**Comment by barche** [comment]
Thanks, glad you like QML.jl!

The way to integrate support takes 2 steps:
1. Add the Qt Quick Extras package to Yggdrasil, using e.g. [Qt5Charts](https://github.com/JuliaPackaging/Yggdrasil/blob/master/Q/Qt5Charts/build_tarballs.jl) as a template.
2. Add the package as an opptional dependency to QML.jl here: https://github.com/barche/QML.jl/blob/926d600d51528e865b7d7d2ef9ba5cfbc868c994/src/QML.jl#L99

Then, you should be able to use the package by adding `using Qt5QtQuickExtras_jll` to your Julia code.

Note that we are currently in the process of upgrading to Qt6, so I think Qt Quick Extras will no longer work there, since Qt Quick Controls 1 is no longer available.

**Comment by hogandp** [comment]
Sounds good, I'll give it a shot!

**Comment by ufechner7** [comment]
Because it doesn't exist for QT 6.x and thats what we are using now I close this feature request.
