### ISSUE TITLE
WebEngineView / WebView

### ISSUE THREAD

**Issue by rasmushenningsson** [JuliaGraphics/QML.jl#200]
Is there any way to create a [WebEngineView](https://doc.qt.io/qt-6/qml-qtwebengine-webengineview.html) or [WebView](https://doc.qt.io/qt-6/qml-qtwebview-webview.html) using QML.jl?

If I try to use `WebEngineView`, I get the error message:
> module "QtWebEngine" is not installed

I might have missed something obvious, but I don't know how to install the WebEngineView module. (Does it require creating a jll with some C++ code etc.?)

My main motivation is to show WGLMakie plots, so if it's more complicated to get this to work than GLMakie, I'm not interested. :laughing:

**Comment by barche** [comment]
There is currently no JLL for the WebView components, because it is difficult to cross-compile the Chromium browser it contains. See https://github.com/JuliaGraphics/jlqml/issues/21

Normally, Makie should work if you restrict its version to 0.17, see the opengl examples here: https://github.com/barche/QmlJuliaExamples

**Comment by rasmushenningsson** [comment]
Ok, thanks!
